version: '3'

services:
  db:
    image: postgres:15
    restart: always
    container_name: category_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      .env
  redis:
    image: redis:7
    container_name: category_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    env_file:
      .env
  fastapi:
    build: ./server
    container_name: category_server
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      .env

volumes:
  pgdata:

networks:
  app-network: