"""add nullable content

Revision ID: 110eb1ac8621
Revises: f28462f97b2b
Create Date: 2025-07-26 17:54:24.128046

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "110eb1ac8621"
down_revision: Union[str, Sequence[str], None] = "f28462f97b2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("category", "content", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("category", "content", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
