"""index

Revision ID: 7c398444661b
Revises: 018e7875f205
Create Date: 2025-07-21 11:11:40.096086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c398444661b'
down_revision: Union[str, Sequence[str], None] = '018e7875f205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    # ### end Alembic commands ###
