"""

Revision ID: ce0c0cd18836
Revises: 7b7f20cf8099
Create Date: 2025-07-27 19:32:22.008090

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce0c0cd18836"
down_revision: Union[str, Sequence[str], None] = "7b7f20cf8099"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category", sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "link")
    # ### end Alembic commands ###
