"""add index, add ondelete param;

Revision ID: e611453d9209
Revises: 018e7875f205
Create Date: 2025-07-20 15:32:52.769368

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e611453d9209"
down_revision: Union[str, Sequence[str], None] = "018e7875f205"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_category_parent_id"), "category", ["parent_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_category_parent_id"), table_name="category")
    # ### end Alembic commands ###
